export const ACTIVITIES_TABLE_LOAD_SUCCESS = 'ACTIVITIES_TABLE_LOAD_SUCCESS'
export const ACTIVITIES_TABLE_ADD_SUCCESS = 'ACTIVITIES_TABLE_ADD_SUCCESS'
export const ACTIVITIES_TABLE_DELETE_SUCCESS = 'ACTIVITIES_TABLE_DELETE_SUCCESS'
export const ACTIVITIES_TABLE_UPDATE_SUCCESS = 'ACTIVITIES_TABLE_UPDATE_SUCCESS'
export const ACTIVITIES_TABLE_FAILED = 'ACTIVITIES_TABLE_FAILED'
export const ACTIVITIES_TABLE_LOAD_REQUEST = 'ACTIVITIES_TABLE_LOAD_REQUEST'





