
export const IT_ASSETS_TABLE_LOAD_SUCCESS = 'IT_ASSETS_TABLE_LOAD_SUCCESS'
export const IT_ASSETS_TABLE_ADD_SUCCESS = 'IT_ASSETS_TABLE_ADD_SUCCESS'
export const IT_ASSETS_TABLE_DELETE_SUCCESS = 'IT_ASSETS_TABLE_DELETE_SUCCESS'
export const IT_ASSETS_TABLE_UPDATE_SUCCESS = 'IT_ASSETS_TABLE_UPDATE_SUCCESS'
export const IT_ASSETS_TABLE_FAILED = 'IT_ASSETS_TABLE_UPDATE_FAILED'
export const IT_ASSETS_REQUEST = 'IT_ASSETS_REQUEST'


