export const EQUIPMENTS_TABLE_REQUEST = 'EQUIPMENTS_TABLE_REQUEST'
export const EQUIPMENTS_TABLE_LOAD_SUCCESS = 'EQUIPMENTS_TABLE_LOAD_SUCCESS'
export const EQUIPMENTS_TABLE_ADD_SUCCESS = 'EQUIPMENTS_TABLE_ADD_SUCCESS'
export const EQUIPMENTS_TABLE_DELETE_SUCCESS = 'EQUIPMENTS_TABLE_DELETE_SUCCESS'
export const EQUIPMENTS_TABLE_UPDATE_SUCCESS = 'EQUIPMENTS_TABLE_UPDATE_SUCCESS'
export const EQUIPMENTS_TABLE_FAILED = 'EQUIPMENTS_TABLE_FAILED'





