export const ENTITY_TABLE_LOAD_SUCCESS = 'ENTITY_TABLE_LOAD_SUCCESS'
export const ENTITY_TABLE_ADD_SUCCESS = 'ENTITY_TABLE_ADD_SUCCESS'
export const ENTITY_TABLE_DELETE_SUCCESS = 'ENTITY_TABLE_DELETE_SUCCESS'
export const ENTITY_TABLE_UPDATE_SUCCESS = 'ENTITY_TABLE_UPDATE_SUCCESS'
export const ENTITY_TABLE_FAILED = 'ENTITY_TABLE_FAILED'





